# Generated by Django 5.2.1 on 2025-06-06 13:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Your full name', max_length=100)),
                ('email', models.EmailField(help_text='Your email address', max_length=254)),
                ('subject', models.CharField(blank=True, help_text='Short subject line', max_length=150)),
                ('body', models.TextField(help_text='What would you like to ask us?')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False, help_text='Mark True once message is handled')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'ordering': ['-timestamp'],
            },
        ),
    ]
