# Generated by Django 5.2.1 on 2025-05-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_pid',
            field=models.CharField(default=1.0, max_length=254),
            preserve_default=False,
        ),
    ]
