# Generated by Django 3.2.25 on 2025-04-24 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the product.', max_length=50)),
                ('description', models.TextField(help_text='Detailed description of the product.')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the product.', max_digits=10)),
                ('image', models.ImageField(blank=True, help_text='Image of the product.', null=True, upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the product was created.')),
            ],
        ),
        migrations.CreateModel(
            name='Grip',
            fields=[
                ('product', models.OneToOneField(help_text='The base product associated with this Grip.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='products.product')),
                ('color', models.CharField(choices=[('black', 'Black'), ('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('white', 'White'), ('pink', 'Pink'), ('orange', 'Orange'), ('yellow', 'Yellow')], help_text='Color of the grip.', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Helmet',
            fields=[
                ('product', models.OneToOneField(help_text='The base product associated with this Helmet.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='products.product')),
                ('color', models.CharField(choices=[('black', 'Black'), ('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('pink', 'Pink')], help_text='Color of the helmet.', max_length=20)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], help_text='Size of the helmet.', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Hurley',
            fields=[
                ('product', models.OneToOneField(help_text='The base product associated with this Hurley.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='products.product')),
                ('grip_color', models.CharField(choices=[('black', 'Black'), ('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('white', 'White'), ('pink', 'Pink'), ('orange', 'Orange'), ('yellow', 'Yellow')], help_text='Color of the grip on the Hurley.', max_length=20)),
                ('weight', models.CharField(choices=[('light', 'Light'), ('medium', 'Medium'), ('heavy', 'Heavy')], help_text='Weight category of the Hurley.', max_length=20)),
                ('size', models.CharField(choices=[('20 inch', '20 inch'), ('22 inch', '22 inch'), ('24 inch', '24 inch'), ('25 inch', '25 inch'), ('26 inch', '26 inch'), ('27 inch', '27 inch'), ('28 inch', '28 inch'), ('29 inch', '29 inch'), ('30 inch', '30 inch'), ('31 inch', '31 inch'), ('32 inch', '32 inch'), ('33 inch', '33 inch'), ('34 inch', '34 inch'), ('35 inch', '35 inch'), ('36 inch', '36 inch'), ('37 inch', '37 inch')], help_text='Size of the Hurley in inches.', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sliotar',
            fields=[
                ('product', models.OneToOneField(help_text='The base product associated with this Sliotar.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='products.product')),
                ('color', models.CharField(choices=[('white', 'White'), ('yellow', 'Yellow')], help_text='Color of the Sliotar.', max_length=20)),
            ],
        ),
    ]
