# Generated by Django 3.2.25 on 2025-04-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hurley',
            name='manufacturer',
            field=models.CharField(blank=True, help_text='Manufacturer of the Hurley.', max_length=50, null=True),
        ),
    ]
