# Generated by Django 3.2.25 on 2025-05-01 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_hurley_manufacturer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grip',
            options={'verbose_name': 'Hurley', 'verbose_name_plural': 'Hurleys'},
        ),
        migrations.AddField(
            model_name='hurley',
            name='type',
            field=models.CharField(choices=[('ash', 'Ash'), ('bambu', 'Bambú'), ('goalie', 'Goalie')], default='ash', help_text='Type of the Hurley.', max_length=20),
        ),
        migrations.AlterField(
            model_name='hurley',
            name='grip_color',
            field=models.CharField(choices=[('black', 'Black'), ('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('white', 'White'), ('pink', 'Pink'), ('orange', 'Orange'), ('yellow', 'Yellow')], default='black', help_text='Color of the grip on the Hurley.', max_length=20),
        ),
        migrations.AlterField(
            model_name='hurley',
            name='manufacturer',
            field=models.CharField(default='Unknown', help_text='Manufacturer of the Hurley.', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hurley',
            name='product',
            field=models.OneToOneField(help_text='The base product associated with this Hurley.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='hurley', serialize=False, to='products.product'),
        ),
        migrations.AlterField(
            model_name='hurley',
            name='weight',
            field=models.CharField(choices=[('light', 'Light'), ('medium', 'Medium'), ('heavy', 'Heavy')], default='medium', help_text='Weight category of the Hurley.', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='products/default-product.jpg', help_text='Image of the product.', null=True, upload_to='products/'),
        ),
    ]
