# Generated by Django 3.2.25 on 2025-05-01 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20250501_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the manufacturer.', max_length=50)),
                ('description', models.TextField(help_text='Short description of the manufacturer.')),
            ],
        ),
        migrations.AlterField(
            model_name='hurley',
            name='manufacturer',
            field=models.ForeignKey(help_text='Manufacturer of the Hurley.', on_delete=django.db.models.deletion.CASCADE, to='products.manufacturer'),
        ),
    ]
